/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "msgrpc.h"

int *get_1_svc(char *argp, struct svc_req *rqstp){
	static int  result = -1;//initially an error




	return &result;
}

int *put_1_svc(struct data *argp, struct svc_req *rqstp){
	static int  result = -1; //initially an error


	return &result;
}
