/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "msgrpc.h"
#include <time.h>



char currentTime[30]; //current time string stored as char array

void getTime(){
	// getting the time -- move this to a method call
	time_t rawtime;
	struct tm *timeinfo;

	// avoid null reference
	if (currentTime == NULL) {
		currentTime[0] = 0;
	}

	// get the current time
	time (&rawtime);
	if (rawtime == ((time_t)-1)) {
		perror("rawtime error");
		currentTime[0] = 0;
		return;
	}

	// convert time to local time
	timeinfo = localtime (&rawtime);
    if (timeinfo == NULL) {
        perror("local time error");
        currentTime[0] = 0;
        return;
    }
}


// uses the fortune program to generate a random string, returns a pointer to that string
char *get_random_string(){
    FILE *fp;

    // variables for creating random string
    char *random_str = NULL;
    char *temp = NULL;

    // use a temporary buffer to incrementally gather results
    char buf[100];

    // maintain size variables for dynamically adjusting the string size
    unsigned int size = 1;
    unsigned int str_length;

    // call fortune to generate a real random string
    fp = popen("fortune", "r");

    // error-check fortune teller response
    if (fp == NULL) {
        perror("Error running fortune to generate random string...");
	    fflush(stderr);
	    if (pclose(fp) == -1){
	        perror("Error closing fortune process...");
	        fflush(stderr);
	    }
	    return "error generating random string...";
    }

    // attain your fortune by writing all string characters to random_str incrementally
    while (fgets(buf, sizeof(buf), fp) != NULL) {
    	// get the current buf size
    	str_length = strlen(buf);
    	// dynamically reallocate the random string with a new size
        temp = realloc(random_str, size + str_length);
        // error-check reallocation
    	if (temp == NULL) {
        	perror("temporary random string memory allocation failed...");
            return "";
        } else {
        	// set the random string on success
        	random_str = temp;
        }
    	// copy the buffer to the random string
        if (strcpy(random_str + size - 1, buf) == NULL){
        	perror("error copying random string...");
        }
        // increase the size variable by the added string length
        size += str_length;
    }

    // error-check closing fortune process
	if (pclose(fp) == -1){
	    perror("Error closing fortune process...");
	    return "error closing fortune process...";
	}
    return random_str;
}





void display_prg_1(char *host){
	CLIENT *clnt;
	int  *result_1;
	int  get_1_arg;
	int  *result_2;
	struct data  put_1_arg;
	int host_id = (int)(rand() % 3);

#ifndef	DEBUG
	clnt = clnt_create (host, DISPLAY_PRG, DISPLAY_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

int i;
for(i = 0; i < 5; i++){
	put_1_arg.id = host_id; //set the host id
	
	char *random_str = "string hereeee";

	if(strcpy(put_1_arg.msg, random_str) == NULL){
		perror("strcopy err");
	}
	free(random_str);
	getTime();

    fflush(stdout);
    printf ("%s Client %d PUT request.\n", currentTime, host_id);
	fflush(stdout);

	result_2 = put_1(&put_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}


	//  return status per project requirements, 
	int status = *result_2;
	fflush(stdout);
	if (status == 0) {
        printf ("%s Success from the server.\n", currentTime);
    } else {
        printf("%s Failure from the server.\n", currentTime);
    }
    fflush(stdout);


    // sleep for 1 second per project requirements
    sleep(1);
}

// sleep for 5 seconds per project requirements
sleep(5);



// client GETs from the server 10 times
int j;
for(j = 0; j < 10; j++){
	get_1_arg = host_id; // set host id
	getTime();
	fflush(stdout);
	printf("%s Client %d has sent a GET request.\n", currentTime, host_id);
	fflush(stdout);

	result_1 = get_1(&get_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	int status2 = *result_2;
	fflush(stdout);
	if (status2 == 0) {
        printf ("%s Success response from the server.\n", currentTime);
    } else {
        printf("%s Failure response from the server.\n", currentTime);
    }
    fflush(stdout);

    sleep(1);
}

	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main(int argc, char *argv[]){
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	display_prg_1 (host);
exit (0);
}
